# Generated by Django 3.2.9 on 2021-12-02 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualwindow',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=10),
        ),
    ]
