# Generated by Django 3.2.9 on 2021-12-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_annualwindow_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualwindow',
            name='magnitud',
            field=models.FloatField(null=True),
        ),
    ]
