# Generated by Django 3.2.9 on 2021-12-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_annualwindow_magnitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualwindow',
            name='g_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualwindow',
            name='g_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualwindow',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annualwindow',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
