# Generated by Django 3.2.9 on 2022-01-03 16:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pollutant_dataset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualwindow',
            old_name='o_x',
            new_name='p_x',
        ),
        migrations.RenameField(
            model_name='annualwindow',
            old_name='o_y',
            new_name='p_y',
        ),
        migrations.RemoveField(
            model_name='annualwindow',
            name='x',
        ),
        migrations.RemoveField(
            model_name='annualwindow',
            name='y',
        ),
        migrations.AlterField(
            model_name='annualwindow',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=4),
        ),
        migrations.CreateModel(
            name='DailyWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateTimeField()),
                ('p_x', models.FloatField(blank=True, null=True)),
                ('p_y', models.FloatField(blank=True, null=True)),
                ('g_x', models.FloatField(blank=True, null=True)),
                ('g_y', models.FloatField(blank=True, null=True)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=15)),
                ('magnitud', models.FloatField(null=True)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=365)),
                ('smoothedValues', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=365)),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pollutant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
            ],
        ),
    ]
