# Generated by Django 3.2.9 on 2022-01-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220103_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualwindow',
            name='g_x',
        ),
        migrations.RemoveField(
            model_name='annualwindow',
            name='g_y',
        ),
        migrations.RemoveField(
            model_name='annualwindow',
            name='p_x',
        ),
        migrations.RemoveField(
            model_name='annualwindow',
            name='p_y',
        ),
        migrations.RemoveField(
            model_name='dailywindow',
            name='g_x',
        ),
        migrations.RemoveField(
            model_name='dailywindow',
            name='g_y',
        ),
        migrations.RemoveField(
            model_name='dailywindow',
            name='p_x',
        ),
        migrations.RemoveField(
            model_name='dailywindow',
            name='p_y',
        ),
    ]
