name: airq
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.7.1
  get: 4.6.1
  flutter: 
    sdk: flutter
  flutter_easyloading: ^3.0.3
  glass_kit: ^2.0.1
  loading_indicator: ^3.0.2
  dropdown_button2: ^1.1.1
  flutter_xlider:
    git:
      url: https://github.com/Ali-Azmoud/flutter_xlider
  fl_chart: ^0.41.0


dev_dependencies: 
  flutter_lints: ^1.0.0
  lint: ^1.8.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

